loki:
  isDefault: false
  tolerations:
    - key: "vendor"
      operator: "Equal"
      value: "cosmotech"
      effect: "NoSchedule"
  nodeSelector:
    "cosmotech.com/tier": "monitoring"

  storage:
    type: 'filesystem'
  
  schemaConfig:
    configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

  limits_config:
    max_entries_limit_per_query: ${LOKI_MAX_ENTRIES_LIMIT_PER_QUERY}

write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0

table_manager:
  enabled: true
  retention_deletes_enabled: true
  retention_period: "${LOKI_RETENTION_PERIOD}"

deploymentMode: SingleBinary
singleBinary:
  replicas: 1