global:
  nodeSelector:
    "cosmotech.com/tier": "services"
  podLabels:
    "networking/traffic-allowed": "yes"
  tolerations:
  - key: "vendor"
    operator: "Equal"
    value: "cosmotech"
    effect: "NoSchedule"

server:
  replicas: ${REPLICAS}
  resources:
    limits:
      cpu: 2
      memory: 750Mi
    requests:
      cpu: 1
      memory: 512Mi
  ingress:
    enabled: false
    ingressClassName: "nginx"
    hostname: ${ARGOCD_DNS_NAME}
    pathType: Prefix
    path: /argocd
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      email: platform@cosmotech.com
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"


configs:
  params:
    server.insecure: true
    server.rootpath: "/argocd"
    server.basehref: "/argocd"