tolerations:
  - key: "vendor"
    operator: "Equal"
    value: "tekton"
    effect: "NoSchedule"
nodeSelector:
  "cosmotech.com/tier": "tekton"
  "kubernetes.io/os": "linux"
serviceAccountName: tekton-triggers-core-interceptors